# Generated by Django 4.2.26 on 2026-04-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='domaine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
